### ISSUE TITLE
Failed to fetch user profile

### ISSUE THREAD

**Issue by blade-demon** [jaredhanson/passport-github#58]
After I configuration for my express4.x server with github, the server shows the error: Failed to fetch user profile. 

**error: at /root/passport-github/examples/login/node_modules/passport-github2/lib/strategy.js:96:19**

**Comment by metzuda** [comment]
Isn't passport-github2 [a different repository](https://github.com/cfsghost/passport-github)?

**Comment by DiegoRBaquero** [comment]
Did you ever solve it?

**Comment by i-break-codes** [comment]
It still happens for me randomly. Though am using `passport-github2` package. Absolutely no idea why as I've checked the creds.. it works for some, fails for some. Not able to reproduce locally either.

**Comment by frankli0324** [comment]
I'm getting the same error on passport-github (not 2), also randomly. I can be sure that the id and the secret are correct because there's a chance (yes, a chance, which means about once per 5,6 requests, weird) that I can login successfully. I'm using version 1.1.0.

**Comment by siyavash4812** [comment]
> I'm getting the same error on passport-github (not 2), also randomly. I can be sure that the id and the secret are correct because there's a chance (yes, a chance, which means about once per 5,6 requests, weird) that I can login successfully. I'm using version 1.1.0.
> 
> traceback:
> 
> ```
> InternalOAuthError: Failed to fetch user profile
>     at /app/node_modules/passport-github/lib/strategy.js:122:19
>     at ClientRequest.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:162:5)
>     at ClientRequest.emit (events.js:198:13)
>     at TLSSocket.socketErrorListener (_http_client.js:401:9)
>     at TLSSocket.emit (events.js:198:13)
>     at emitErrorNT (internal/streams/destroy.js:91:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
> ```
> 
> upate: it's not the library's fault... seems that my dns provider is returning different ip addresses for api.github.com, some of which is unavailable.
> 
> I wish passport-github could have a better error presentation though

I had the same issue and changing the DNS helped me. This is a tutorial on how to change DNS in Mac (I recommend cloudflare)
https://www.macinstruct.com/tutorials/how-to-change-your-macs-dns-servers/
